name: climpred-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - tqdm
  - netcdf4
  - cftime>=1.5.0
  - xarray>=0.19.0
  - dask-core
  # Regridding
  - esmpy=*=mpi*  # Ensures MPI works with version of esmpy.
  - xesmf
  - xskillscore>=0.0.20
  - xrft
  - xclim>=0.30.0
  - bias_correction
  # Visualization
  - matplotlib-base
  - nc-time-axis>=1.4.0 
